markdown: kramdown
pygments: true
safe: false
permalink: /posts/:year/:month/:day/:title.html
exclude:
  - README.md

name: Desert
host: furtherlee.github.com

custom:
    category:
        default: Default Category
        another: Another Category
    categories:
      - name:  default
        title: Default Category

      - name:  another
        title: Another Category

meta:
    author:
        name: Li Shijian
        email: 95588lsj@gmail.com
        disqus: blogoffurtherlee              # Disqus缩略标识
        gcse: 003444772476076490850:lpop8pglar4  # Google自定义搜索标识ID
        github: furtherLee                 # GitHub账号
        gravatar: a9a1acd402ef13a85a72ee2912848807  # Gravatar头像标识
	
    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
