# -*- coding: utf-8 -*-
markdown: kramdown
pygments: true
safe: false
permalink: /posts/:year/:month/:day/:title.html
exclude:
  - README.md

name: Desert
host: furtherlee.github.com

custom:
    category:
        default: Default Category
	community: Community Category
        bookcase: Bookcase Category
    categories:
      - name:  bookcase
        title: 书架

      - name: community 
        title: 圈子

      - name:  default
        title: 杂七杂八

meta:
    author:
        name: Li Shijian
        email: 95588lsj(at)gmail.com
        disqus: blogoffurtherlee              # Disqus缩略标识
        gcse: 003444772476076490850:lpop8pglar4  # Google自定义搜索标识ID
        github: furtherLee                 # GitHub账号
        gravatar: a9a1acd402ef13a85a72ee2912848807  # Gravatar头像标识
        twitter: FurtherLee
        facebook: lsj1990
    
    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
